language: generic
cache:
  - docker
  - directories:
    - vendor
services:
  - docker
script: ./script/cibuild
branches:
  only:
  - master
#env:
#  global:
#  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: script
  script: ./script/deploy
  skip_cleanup: true
  on:
    branch: master
