services:
  site:
    read_only: true
    command: jekyll serve
    image: jekyll/jekyll:stable
    tmpfs:
      - /var/tmp
    environment:
      - TMPDIR=/var/tmp
    volumes:
      - .:/srv/jekyll
      - ./vendor/home/jekyll:/home/jekyll
      - ./vendor/usr/gem:/usr/gem
      - ./vendor/var/jekyll:/var/jekyll
      - ./vendor/bundle:/usr/local/bundle

    ports:
      - 4000:4000
      # - 8124:8124 # PostCSS Server
      # - 35729:35729 # Jekyll live-reload, listens on localhost so not accessible
