version: "3"
services:
  site:
    command: jekyll serve
    image: jekyll/jekyll:stable
    tmpfs:
      - /tmp
    volumes:
      - .:/srv/jekyll
      - ./vendor/usr/gem:/usr/gem
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729
      - 3000:3000
      - 80:4000
