name: Build and publish gh-pages website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      # must be able to write to the gh-pages branch
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # cache gems
      - name: Cache
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Jekyll
      - name: Build site with Jekyll
        uses:  helaili/jekyll-action@v2
        with:
          build_only: true
          build_dir: _site
          jekyll_src: _source
          jekyll_build_options: "--config _config.yml"

      - name: HTML proofer
        uses: docker://18fgsa/html-proofer
        with:
          args: /github/workspace/_site --disable-external --empty-alt-ignore --url-ignore "/^#$/"

      - name: HTML5 validator
        uses: docker://logicly/html5validator
        with:
          entrypoint: html5validator
          args: --root /github/workspace/_site

      # check GH Pages status
      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v4
        with:
          pages_threshold: major_outage

      # Commit _site as gh-pages branch
      #- name: Deploy to GitHub Pages
      #  if: success()
      #  uses: crazy-max/ghaction-github-pages@v4
      #  with:
      #    build_dir: _site
      #    fqdn: www.validator.com.au
      #    jekyll: false
      #    target_branch: gh-pages
      #  env:
      #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site

